= ansible-role-openssh
Jonas Pammer <opensource@jonaspammer.at>;
:toc:
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Very Relevant Status Badges
https://github.com/JonasPammer/ansible-role-openssh/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-openssh/actions/workflows/ci.yml/badge.svg[Testing CI]]

// Badges about Conventions in this Project
https://conventionalcommits.org[image:https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg[Conventional Commits]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-openssh/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-openssh/master.svg[pre-commit.ci status]]
// image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]
https://open.vscode.dev/JonasPammer/ansible-role-openssh[image:https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc[Open in Visual Studio Code]]
image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome]


ifdef::env-github[]
[TIP]
__A single-page version of this README can be found at https://JonasPammer.github.io/ansible-role-openssh[
JonasPammer.github.io/ansible-role-openssh].__
endif::[]


An Ansible role for installing and configure openssh-server.


toc::[]

[[meta]]
== 🔎 Metadata
Below you can find information on…

* the role's required Ansible version
* the role's supported platforms
* the role's https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-dependencies[role dependencies]

.link:meta/main.yml[]
[source,yaml]
----
include::meta/main.yml[]
----


[[requirements]]
== 📌 Requirements
// Any prerequisites that may not be covered by this role or Ansible itself should be mentioned here.
The Ansible User needs to be able to `become`.


The https://galaxy.ansible.com/community/general[`community.general` collection]
must be installed on the Ansible controller.

The https://galaxy.ansible.com/ansible/posix[`ansible.posix` collection]
must be installed on the Ansible controller.


[[variables]]
== 📜 Role Variables
// A description of the settable variables for this role should go here
// and any variables that can/should be set via parameters to the role.
// Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.)
// should be mentioned here as well.

Please refer to the https://man.openbsd.org/ssh_config.5[official ssh_config(5) BSD man page]
for further documentation of all these configuration options.



=== `/etc/ssh/ssh_config`

These variables are all used in the templates for the system-wide `/etc/ssh/ssh_config` configuration file.

[source,yaml]
----
openssh_port: 22
----
[NOTE]
This role configures SELinux's network ports definitions to allow this port.

[source,yaml]
----
openssh_address_family: any
----


[source,yaml]
----
openssh_listen_addresses:
  - "0.0.0.0"
  - "::"
----


[source,yaml]
----
openssh_host_keys:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ed25519_key
----
[NOTE]
This role ensures that the above mentioned default host key types exist, always.

[source,yaml]
----
openssh_rekey_limit: default none
----


[source,yaml]
----
openssh_syslog_facility: AUTH
----


[source,yaml]
----
openssh_loglevel: INFO
----


[source,yaml]
----
openssh_login_grace_time: 2m
openssh_permit_root_login: "yes"
openssh_strict_modes: "yes"
openssh_max_auth_tries: 6
openssh_max_sessions: 10
----


[source,yaml]
----
openssh_pub_key_authentication: "yes"
----


[source,yaml]
----
openssh_authorized_key_file: ".ssh/authorized_keys"
----


[source,yaml]
----
openssh_authorized_prinicpals_file: none
openssh_authorized_keys_command: none
openssh_authorized_keys_command_user: nobody
----


[source,yaml]
----
openssh_host_based_authentication: "no"
openssh_ignore_user_known_hosts: "no"
openssh_ignore_rhosts: "yes"
----


[source,yaml]
----
openssh_permit_empty_passwords: "no"
openssh_password_authentication: "yes"
----


[source,yaml]
----
openssh_challenge_response_authentication: "no"
----


[source,yaml]
----
openssh_gssapi_authentication: "yes"
openssh_gssapi_cleanup_credentials: "no"
openssh_gssapi_strict_acceptor_check: "yes"
openssh_gssapi_key_exchange: "no"
openssh_gssaip_enable_k5_users: "no"
----


[source,yaml]
----
openssh_use_pam: "yes"
----


[source,yaml]
----
openssh_allow_agent_forwarding: "yes"
openssh_allow_tcp_forwarding: "yes"
openssh_gateway_ports: "no"
openssh_x11_forwarding: "yes"
openssh_x11_display_offset: 10
openssh_x11_use_localhost: "yes"
openssh_permit_tty: "yes"
----


[source,yaml]
----
openssh_print_motd: "no"
----


[source,yaml]
----
openssh_print_last_log: "yes"
openssh_tcp_keep_alive: "yes"
openssh_permit_user_environment: "no"
openssh_compression: delayed
openssh_client_alive_interval: 30
openssh_client_alive_count_max: 3
openssh_show_patch_level: "no"
openssh_use_dns: "no"
openssh_pid_file: /var/run/sshd.pid
openssh_max_startups: "10:30:100"
openssh_permit_tunnel: "no"
openssh_chroot_directory: none
openssh_version_addendum: none
----


[source,yaml]
----
openssh_banner: none
----


[source,yaml]
----
openssh_accept_envs:
  - LANG
  - LANGUAGE
  - LC_ADDRESS
  - LC_ALL
  - LC_COLLATE
  - LC_CTYPE
  - LC_IDENTIFICATION
  - LC_MEASUREMENT
  - LC_MESSAGES
  - LC_MONETARY
  - LC_NAME
  - LC_NUMERIC
  - LC_PAPER
  - LC_TELEPHONE
  - LC_TIME
  - XMODIFIERS
----


[source,yaml]
----
openssh_subsystem: sftp {{ openssh__sftp_server }}
----


[source,yaml]
----
openssh_trusted_user_ca_keys: none
----
Specifies a file containing public keys of certificate authorities that are
trusted to sign user certificates for authentication, or none to not use one.

[source,yaml]
----
# openssh_allow_users: root
# openssh_allow_groups: wheel
----
Restrict access to this (space separated list) of users or groups.
For example: `openssh_allow_users: root my_user`, `openssh_allow_groups: wheel my_group`

[source,yaml]
----
openssh_restart_immediately: false
----
Whether to restart openssh immediately or after
all other Ansible tasks have been completed.



[[dependencies]]
== 👫 Dependencies
// A list of other roles should go here,
// plus any details in regard to parameters that may need to be set for other roles,
// or variables that are used from other roles.



[[example_playbooks]]
== 📚 Example Playbook Usages
// Including examples of how to use this role in a playbook for common scenarios is always nice for users.

[NOTE]
====
This role is part of https://github.com/JonasPammer/ansible-roles[
many compatible purpose-specific roles of mine].

The machine needs to be prepared.
In CI, this is done in `molecule/default/prepare.yml`
which sources its soft dependencies from `requirements.yml`:

.link:molecule/default/prepare.yml[]
[source,yaml]
----
include::molecule/default/prepare.yml[]
----

The following diagram is a compilation of the "soft dependencies" of this role
as well as the recursive tree of their soft dependencies.

image:https://raw.githubusercontent.com/JonasPammer/ansible-roles/master/graphs/dependencies_openssh.svg[
requirements.yml dependency graph of jonaspammer.openssh]
====

.Minimum Viable Play
====
[source,yaml]
----
roles:
    - "jonaspammer.openssh"

vars:
    some_var: "some_value"
----
====


[[development]]
== 📝 Development
include::DEVELOPMENT.adoc[]


[[contributing]]
== 💪 Contributing
include::CONTRIBUTING.adoc[]


[[changelog]]
== 🗒 Changelog
Please refer to the
https://github.com/JonasPammer/ansible-role-openssh/releases[Release Page of this Repository]
for a human changelog of the corresponding
https://github.com/JonasPammer/ansible-role-bootstrap/tags[Tags (Versions) of this Project].

Note that this Project adheres to Semantic Versioning.
Please report any accidental breaking changes of a minor version update.


[[license]]
== ⚖️ License

.link:LICENSE[]
----
include::LICENSE[]
----
