---
roles:
  - name: jonaspammer.bootstrap
  - name: robertdebock.selinux
collections:
  - name: community.docker # only needed for molecule execution
  - name: community.general
  - name: ansible.posix
