---
roles:
  - name: jonaspammer.bootstrap
  - name: robertdebock.selinux
# NOTE: list all collections used here (even if included in `ansible`)
collections:
  - name: community.general
  - name: ansible.posix
