---
# tasks file of ansible-role jonaspammer.openssh

- name: check if all variables have been set correctly
  ansible.builtin.import_tasks: assert.yml
  run_once: true
  delegate_to: localhost

- name: Install openssh from system package manager.
  ansible.builtin.package:
    name: "{{ openssh__packages }}"
    state: present

- name: Configure SELinux to allow openssh_port.
  community.general.seport:
    ports: "{{ openssh_port }}"
    proto: "tcp"
    setype: "ssh_port_t"
    state: "present"
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"

- name: Generate host keys.
  ansible.builtin.command:
    cmd: "/usr/bin/ssh-keygen -q -t {{ item }} -f /etc/ssh/ssh_host_{{ item }}_key -C '' -N ''"
    creates: "/etc/ssh/ssh_host_{{ item }}_key"
  loop: "{{ openssh__key_types }}"

- name: make run directory
  ansible.builtin.file:
    path: "{{ openssh__run_directory }}"
    state: directory
    mode: u=rwx,g=rx,o=rx
  when:
    - ansible_os_family == "Debian"

- name: Generate OpenSSH Configuration.
  ansible.builtin.template:
    dest: "{{ openssh__configuration_file }}"
    src: "{{ openssh__template_src }}"
    mode: "{{ openssh__template_mode }}"
    owner: root
    group: root
    validate: sshd -f %s -t
  notify:
    - restart openssh

- name: Start and enable openssh service.
  ansible.builtin.service:
    name: "{{ openssh__service }}"
    state: started
    enabled: true

- name: flush handlers
  meta: flush_handlers
  when:
    - openssh_restart_immediately
