---
# handlers file of ansible-role jonaspammer.openssh

- name: restart openssh
  ansible.builtin.service:
    name: "{{ openssh__service }}"
    state: restarted
  when:
    - not ansible_check_mode
    - not openssh_restart_immediately
